[project]
name = "file-summarizer"
version = "0.1.0"
description = "MCP server to summarize files or texts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.2",
]
